export default {
  HomeButtonToolTip: "初始视图",
  Imagery: "影像",
  Terrain: "地形",
  Other: "其他",
  "Bing Maps Aerial": "必应航空地图",
  "Bing Maps Aerial with Labels": "必应航空地图（带标注）",
  "Bing Maps Roads": "必应道路地图",
  "Sentinel-2": "哨兵卫星影像-2",
  "Blue Marble": "蓝色弹珠",
  "Earth at night": "地球之夜",
  "Natural Earth&nbsp;II": "自然地球II",
  "ESRI World Imagery": "ESRI 影像",
  "ESRI World Street Map": "ESRI 道路",
  "ESRI National Geographic": "ESRI 自然地理",
  "Open­Street­Map": "Open­Street­Map矢量",
  "Stamen Watercolor": "雄蕊彩色",
  "Stamen Toner": "雄蕊黑白",
  "WGS84 Ellipsoid": "WGS84 椭球",
  "Cesium World Terrain": "Cesium 世界地形图",

  ">Mouse": ">鼠标",
  ">Touch": ">手势",
  "Left click + drag": "左键+拖拽",
  "Right click + drag, or": "右键+拖拽，或者",
  "Mouse wheel scroll": "滚动鼠标滚轮",
  "Middle click + drag, or": "中键 + 拖动,或者",
  "CTRL + Left/Right click + drag": "CTRL +左/右 单击+拖拽",
  "One finger drag": "单指拖动",
  "Two finger pinch": "双指捏合",
  "Two finger drag, same direction": "双指同向拖动",
  "Two finger drag, opposite direction": "双指反向拖动",

  "Pan view": "平移",
  "Zoom view": "缩放",
  "Rotate view": "旋转",
  "Tilt view": "倾斜视图",

  GeocodersPlaceholder: "请输入地名或坐标",

  SceneModePickerToolTip2D: "二维",
  SceneModePickerToolTip3D: "三维",
  SceneModePickerToolTipView: "哥伦布视图",

  NavigationInstructions: "帮助",
  "Mapbox Satellite": "Mapbox 卫星影像",
  "Mapbox Streets": "Mapbox 道路",
  "Mapbox Streets Classic": "Mapbox 道路（分类）",

  NavigationHelpButtonToolTip: "操作指南",
  enterFullScreen: "全屏",
  exitFullScreen: "退出全屏",
}